version: '3.7'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
    - "2181:2181"
    hostname: zookeeper
  kafka1:
    container_name: kafka1
    image: wurstmeister/kafka:2.12-2.2.1
    command: [start-kafka.sh]
    ports:
    - "9092:9092"
    hostname: kafka1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 0
      BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - "zookeeper"
  kafka2:
    container_name: kafka2
    image: wurstmeister/kafka:2.12-2.2.1
    command: [start-kafka.sh]
    ports:
    - "9093:9092"
    hostname: kafka2
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 1
      BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - "zookeeper"
  kafka3:
    container_name: kafka3
    image: wurstmeister/kafka:2.12-2.2.1
    command: [start-kafka.sh]
    ports:
    - "9094:9092"
    hostname: kafka3
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 2
      BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - "zookeeper"
