version: '3.7'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
    - "2181:2181"
    hostname: zookeeper
  kafka1:
    container_name: kafka1
    image: wurstmeister/kafka:2.12-2.2.1
    command: ["start-kafka.sh"]
    ports:
    - "9092:9092"
    hostname: kafka1
    environment:
      KAFKA_CREATE_TOPICS: "connect_file_text:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 0
      BOOTSTRAP_SERVERS: kafka1:9092
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - "zookeeper"
  kafka-worker:
    container_name: worker
    image: wurstmeister/kafka:2.12-2.2.1
    command: ["/opt/kafka/bin/connect-standalone.sh", "/opt/kafka/connect-standalone.properties", "/opt/kafka/connect-file-source.properties"]
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - type: bind
      source: ./input.txt
      target: /opt/kafka/input.txt
    - type: bind
      source: ./storage
      target: /tmp/storage/
    - type: bind
      source: ./connect-standalone.properties
      target: /opt/kafka/connect-standalone.properties
    - type: bind
      source: ./connect-file-source.properties
      target: /opt/kafka/connect-file-source.properties
    depends_on:
    - "kafka1"
